name: Build Mod

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Gradle
        run: ./gradlew.bat build

      - name: Upload built JAR
        uses: actions/upload-artifact@v3
        with:
          name: mod-jar
          path: build/libs/*.jar
